---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1nu6df8rvf38s8wsh5tef2fwu8umtx4evzjmfjktar866ehqkkfhqfqmaek
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1nu6df8rvf38s8wsh5tef2fwu8umtx4evzjmfjktar866ehqkkfhqfqmaek
