apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:+9YOhkh4+3gwgrAWlh32RYCXopOhYiF/r/MqZA2FU8dFWIOOelpR/Q==,iv:8xDYriwWOMK7K4MtipXaYhB99BwZ/eT+nUO9d0poAnI=,tag:2jc2Ho2WrnFHWDctyakQVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nu6df8rvf38s8wsh5tef2fwu8umtx4evzjmfjktar866ehqkkfhqfqmaek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOG0xMnhuanY4dUp4SHRo
            YlV0a3FXV1JReC9Id0Y3UFRza0czdktnMnhBCjRQb2NXWlM0RlZhVUt1MCtnNHNW
            WGk1RGxtejdhdzkzZzEwTGMzNFBaQmMKLS0tIDZuMHpkTHVJWFZ5RytNZTcreWpN
            aVRBYnNNMHR0WjBKYmpyZG1oVzVuelEKkV3bTxsyAYIYt4SEx+l9+0ASELhRgsf9
            m661iCdrjYuyujDnhSuOLt7LeT5xFuUxvmMNn2q+niUa0lN2t4gauw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-19T21:28:29Z"
    mac: ENC[AES256_GCM,data:2Zy7hWMqr8fXUaxvPTifgJ9VBPtBMvjbpUPooRaQhoYi4P3Ex0+nHcMp4Wzz/TY4AwOZjFBv98v2ygylxg3q0og9eVS1X9yLSQ48KCRWbKyBiH0W8WnhO05tg5M+oHa0dfLCiw41k2b9saQ5pUP/O0C7vgUFSpocqPYCVEBUCIU=,iv:iy+fncEiypqKtqc5hoQTAXLB6gb7OT8ho2r36Q3Uzbw=,tag:k8i8kF+StDdGzBAf9pRhlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
