---

# ssh_authorized_keys: []

archlinux:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm_sensors
    - nano
    - nfs-utils
    - nvme-cli
    - socat
    - python-kubernetes
    - python-yaml
