apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ne3JiLs=,iv:BZLMvxspRwckH555fZNJ8VnpEbmuHETPqaIAXsqZ12U=,tag:OuHmjyoPPdgA4IDpDjyRUA==,type:str]
    password: ENC[AES256_GCM,data:E0CHWP5/xckZfRyG/7JjWnV/JCB1jd0+MXFYutoUOOS8NoeGyJjuqkX3AbwyyDuT2LG4TJAEk/pO85nx,iv:oViJRZDZfTzqq9dc6qBMjHar9JP/vZtXlvvXPGAHcp0=,tag:/vxb84GMF9XavfOlxc7nxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nu6df8rvf38s8wsh5tef2fwu8umtx4evzjmfjktar866ehqkkfhqfqmaek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZkZwcEc1c0pVSHRBcXVE
            VVNpdy9jRCtlV2xkUlJRZm1sbGtwcW1vQUNnCllUS2tld0d1QnRZSTBSK0N4R0hs
            UTRyRU55ZVhGZ2t2dkNwVkx6b1Btc2cKLS0tIGw3a08zMGxadU5mZ0ZyVnJORktk
            SU9Lb2h0R2kwZTh4TzVveVNqd2lXOVkK8bkD0oVvQ/HAZuEDWPWEafmPWeeJQmxv
            7Tt6pzaO9xdqLmQnKOBkN7vynm9R+ySQ+zj/cmnGk6e5qrmYUCPKJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-19T21:28:30Z"
    mac: ENC[AES256_GCM,data:QkVhZeHTYOuom/uusv772H1d5vUYVwc+69NgQlox/XBnPmGRkj9X2r6cinZQE16VUZ0Bni225b9Fkj0xwdrVP1mUFoakrbD7dHQaBoU/3lt1nhjgOyUe/Ba3dTS65fGrvdwQ47BXyOsfXgWEhUBOq4HXF8YAqUJGZUNVP18rYdE=,iv:pJHHszfVVhdaxjlgU7fmpou/d8ditIN2kfulcaZ0fcA=,tag:qSocr2PauLwGnniX8YU7cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
