---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  METALLB_LB_RANGE: "10.13.100.100-10.13.100.200"
  METALLB_K8S_GATEWAY_ADDR: "10.13.100.101"
  METALLB_INGRESS_ADDR: "10.13.100.102"
  KUBE_VIP_ADDR: "10.13.100.201"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
